### PR TITLE
Packages storage

### PR DESCRIPTION
**Pull request by vsapronov**

### CODE REVIEW

**Comment by rlmartin** [comment]
@vsapronov can you add some minor commentary on the other one-off registries and why it makes sense to use a single one to cover all? Maven, npm, ECR, etc

**Comment by rlmartin** [comment]
Otherwise, 👍

**Comment by ruxy** [comment]
👍

**Comment by vdumitrescu** [comment]
Artifactory 👍

**Comment by semenodm** [comment]
Artifactory

**Pull request merged**
