### PR TITLE
Kotlin vs Scala

### PR DESCRIPTION
**Pull request by rlmartin**
This PR is intended to drive a discussion/decision on Kotlin vs Scala as the primary language of choice for "long-running, request/response microservices" - related to https://github.com/ModaOperandi/rfc/pull/8. Out of scope are language choices/recommendation for other disciplines, i.e. Data Science, serverless, tooling, frontend, etc.

The end result of this will be to merge one of the two sections to master, and completely remove the other.

### CODE REVIEW

**Comment by vsapronov** [comment]
Kotlin <- my vote
We already have some Java codebase that is more easy to move to Kotlin then to Scala. Kotlin is simpler- easier to learn. Kotlin is newer - more marketing benefits from advertizing company as a "Kotlin shop".

**Comment by semenodm** [comment]
Scala

**Comment by barryoneill** [comment]
Scala.  I'm biased towards Scala from experience, but at the end of the day, the argument that Kotlin is easier to learn doesn't necessarily translate to better apps.  If I'm going to use a functional language for prod code, I'll use one that has hardened frameworks with lots of production exposure.  I know there's an opinion that maintaining multiple languages/tooling carries an overhead, but if we're following good conventions, with code generation and quality test coverage I'm not so opposed to it.

**Comment by ajpolt** [comment]
Obviously either language would work just fine from a technical perspective or else we wouldn't even be discussing this, so I'll leave language features out of this. The most pertinent consideration to me, then, is talent acquisition, and I think that argument is in favor of Kotlin.

Recruiting for a very specific skillset at Moda is not the easiest, as I've found while trying to recruit iOS developer friends and randoms on LinkedIn/Hired.com/etc. As Vlad mentioned, "we're a Kotlin shop" is a differentiator, and if that makes the right folks give us a second look then it's almost worth it by itself. I don't think Scala has the same power to differentiate us from all the other companies out there.

Also, re: easy to learn, transitioning from Java it took me maybe a day or two to feel comfortable and a week or so to really feel like I had a solid grasp on the language. Barry wrote above that "the argument that Kotlin is easier to learn doesn't necessarily translate to better apps" and that is absolutely true, but it does make it easier to recruit solid devs who don't necessarily have experience with Scala.

**Comment by upperbounds** [comment]
I'm picking Kotlin for the following reasons:
* For those newer to the language it is quite easy to write readable, idiomatic code; especially for those coming from either a Java or dynamic language background (Ruby and Typescript especially)
* I feel Kotlin is sufficiently polished with reasonable tools (sheesh... I was feeling productive enough while using Emacs).
* I can see immediate opportunities to improve our business that fit nicely with Kotlin. For example, I think we could quite easily and quickly reimplement our purchase order PDFs to look more professional, generate faster and not be in Mojo.
* I think Kotlin has a pretty good starting story for immutability, nullability protection, and programming with functions.  Future language features (KEEP-87) and libraries like Arrow might help scratch the typed FP itch, though it will never compete with Haskell in that domain.

Personal note:
I haven't done work in Scala for quite some time.  While I can appreciate the language for introducing me to a lot of novel concurrency patterns and typed FP, I don't think back fondly of fighting with sbt, nor the confusing indirection in the standard lib (CanBuildFrom, natch), et al. Presumably the language and tools have matured and become more polished; however, the window for my enthusiasm closed a while back.  I'm also reluctant to start new projects in a language that is currently in the middle of a massive compiler redesign.

...and that logo is absolutely dreadful.

**Comment by rlmartin** [comment]
Scala

- More existing knowledge/experience, both internally and with external candidates; many senior people already have experience with Scala - at least _some_ people wouldn't be ramping up on the language
- Breadth of how people can approach the language - entry-level OOP up to FP. Allows for a progression for people if they are interested
- Akka Actors
- More mature ecosystem (tooling, documentation, online lessons, frameworks)

**Comment by figgybit** [comment]
Scala

**Comment by EdSancha** [comment]
I'm a bit more partial to Scala based in my personal experience, coming from Swift it wasn't that hard to get used to the syntax and I like the immutability of the code as a default. Scala is also a stablished language in backend development whereas Kotlin or Swift, which could be considered at the same level if a non-JVM language was considered, are a bit more limited in that sense. A big plus is Scala's Sever and Client APIBuilder support. Kotlin only has client support (which I'm not sure would work in the backend)

**Pull request merged**
